# Generated by Django 3.1.7 on 2021-03-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_auto_20210329_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
