# Generated by Django 3.1.7 on 2021-03-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_auto_20210329_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='photo',
        ),
        migrations.AddField(
            model_name='menu',
            name='photo1',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='photo2',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='photo3',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
