# Generated by Django 3.1.7 on 2021-03-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_auto_20210330_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('phone_no', models.TextField(max_length=20)),
                ('hairMenu', models.CharField(choices=[('cut', 'Cut'), ('perm', 'Cantaloupes'), ('straight', 'Mangoes'), ('color', 'Color'), ('shampoo', 'Shampoo')], max_length=10)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='photo1',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='photo3',
        ),
    ]
