# Generated by Django 3.1.7 on 2021-03-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_auto_20210330_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
