# Generated by Django 3.1.7 on 2021-03-31 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salon', '0012_auto_20210331_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salon.menu'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
