# Generated by Django 3.1.7 on 2021-03-31 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salon', '0013_auto_20210331_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stylist',
            name='hairMenu',
        ),
        migrations.AddField(
            model_name='stylist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
