# Generated by Django 3.1.7 on 2021-04-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0014_auto_20210331_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=None),
        ),
    ]
