# Generated by Django 3.1.7 on 2021-04-01 07:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0015_auto_20210401_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stylist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='salon.stylist'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
